import {
    LineChart,
    Line,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    Legend,
    ResponsiveContainer,
} from 'recharts';

// Define the interface for the data prop
interface RevenueData {
    name: string; // This represents the name or label for each data point
    doctorRevenue: number; // Revenue generated by doctors
    adminRevenue: number; // Revenue generated by the admin
}

interface RevenueChartProps {
    data: RevenueData[]; // Array of revenue data objects
}

const RevenueChart: React.FC<RevenueChartProps> = ({ data }) => {
    return (
        <ResponsiveContainer width="95%" height="100%">
            <LineChart
                data={data}
                margin={{
                    top: 5,
                    right: 30,
                    left: 20,
                    bottom: 5,
                }}
            >
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" tickCount={12} />
                <YAxis />
                <Tooltip />
                <Legend />
                <Line
                    type="monotone"
                    dataKey="doctorRevenue"
                    stroke="#8884d8"
                    activeDot={{ r: 8 }}
                    name="Doctor Revenue"
                />
                <Line
                    type="monotone"
                    dataKey="adminRevenue"
                    stroke="#82ca9d"
                    name="Admin Revenue"
                />
            </LineChart>
        </ResponsiveContainer>
    );
};

export default RevenueChart;
